name: Release

on:
  push:
    branches:
      - master

jobs:
  archive:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Variables
      run: echo "ARCHIVE_NAME=${GITHUB_REPOSITORY_NAME}-$(echo $GITHUB_REF | sed 's/refs\/heads\///')-${GITHUB_SHA}.tar.gz" >> $GITHUB_ENV

    - name: Prepare Staging Directory
      run: |
        mkdir -p /tmp/staging
        cp -r ${{ github.workspace }}/* /tmp/staging/
        rm -rf /tmp/staging/.git /tmp/staging/var/log /tmp/staging/tmp 
    
    - name: Archive Repository
      run: tar -czvf ${ARCHIVE_NAME} -C /tmp/staging .

    - name: Upload Archive as Artifact
      uses: actions/upload-artifact@v2
      with:
        name: repository-archive
        path: ${{ env.ARCHIVE_NAME }}
