name: Release

on:
  push:
    branches:
      - master

jobs:
  archive:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Variables
      run: echo "ARCHIVE_NAME=${GITHUB_REPOSITORY_NAME}-$(echo $GITHUB_REF | sed 's/refs\/heads\///')-${GITHUB_SHA}.tar.gz" >> $GITHUB_ENV

    - name: Prepare Staging Directory
      run: |
        mkdir -p /tmp/staging
        cp -r ${{ github.workspace }}/* /tmp/staging/
        rm -rf /tmp/staging/.git /tmp/staging/var/log /tmp/staging/tmp 
    
    - name: Archive Repository
      run: tar -czvf ${ARCHIVE_NAME} -C /tmp/staging .

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: ssa_${{ GITHUB_SHA }}
        release_name: rendgen ${{ GITHUB_SHA }}
        body: |
          branch: ${{ github.ref_name }}
          triggered by: ${{ github.actor }}
        draft: false
        prerelease: false

    - name: Upload Release Assets
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ env.ARCHIVE_NAME }}
        asset_name: ${{ env.ARCHIVE_NAME }}
